Added initial LineByLineAccessibility implementation
NYPL-Simplified/line-by-line-accessibility pull request #2
Opened 2017-02-21 21:32 UTC by winniequinn

2017-02-21 22:27 UTC, aslagle requested changes
This looks great and is very well-documented :)

I only had minor comments, but I would like to see some tests. It would be helpful to be able to look at examples of what this does with different inputs.

2017-02-21 22:27 UTC, aslagle commented on src/LineByLineAccessibility.ts
> + * accessibilty. */
I'm not sure what it means to analyze a document for line-by-line accessibility. It sounds like you're taking a document and checking if it's accessible. Maybe I'd say you're processing it for accessibility?

2017-02-21 22:27 UTC, aslagle commented on src/LineByLineAccessibility.ts
> +  pageWidth: number;
Why don't you expose the height as well?

2017-02-21 22:27 UTC, aslagle commented on src/LineByLineAccessibility.ts
> +          // like <span>foo</span><span>bar</span>.
I don't understand why you need to add a space, when there are whitespace entries in `words` already. This doesn't lead to extra space?

2017-02-21 22:27 UTC, aslagle commented on src/LineByLineAccessibility.ts
> +    initalClientRect: ClientRect)
You have a typo in initial.

2017-02-21 22:27 UTC, aslagle commented on src/LineByLineAccessibility.ts
> +        || onNextPage;
Is this the part that handles hyphenated words? How does that work?

2017-02-21 22:32 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +    initalClientRect: ClientRect)
Eep! Will fix!

2017-02-21 22:55 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +    initalClientRect: ClientRect)
Fixed in c2582746b5be89ac9968237973f96fd14937555e.

2017-02-21 22:56 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +          // like <span>foo</span><span>bar</span>.
Very good catch! I suppose this was just never removed when I put in the more faithful whitespace preservation above.

2017-02-21 22:57 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +          // like <span>foo</span><span>bar</span>.
Fixed in 4ced4ad184e95722452d3850d047130521ae46d8.

2017-02-21 22:58 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> + * accessibilty. */
Let me take another shot at it!

2017-02-21 23:02 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> + * accessibilty. */
Fixed in c2582746b5be89ac9968237973f96fd14937555e.

Please let me know if you still think this needs some work!

2017-02-21 23:15 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +        || onNextPage;
The word hyphenation bit is sort of strange and I should probably document what happens somewhere.

Basically, you will have a document that looks something like this in a browser:

```
aaaa bbb ccccc ddd-
ddd eee ffffff gggg.
```

The value of the text node above is `aaaa bbb ccccc ddd-ddd eee ffffff gggg`. Because our code only considers words to be separated by whitespace, it will treat the above as seven words (which is a good thing).

When our code is getting the rectangle for `ddd-ddd`, it will get a rectangle that covers both lines. (If you think about it for a moment, it would have to!) As such, the left side of the rectangle is prior to the rectangle for `ccccc` and thus `ddd-ddd` is grouped onto the next line (because of the `rect.left <= lastLeft` check at a minimum).

While this does do a good job of assigning each word an arguably correct line, it does mean that the unioned rectangle for the second line may cover the rectangle for the first line. This happens to not be a problem in practice because the rectangle for the first line appears before the rectangle for the second line in the processed document and rectangles happen to be searched in the same order they appear in the document when doing touch detection in native code, but yes, this is not at all clear! I sort of fumbled my way into a good solution for this awhile ago and didn't record it properly.

I'm not sure how quite to cram all of this into the source code but I'll figure out something! I also need to double-check what happens when the browser is doing its own hyphenation _and_ what happens when a hyphenated word is broken over two pages (if that's possible).

2017-02-21 23:37 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +  pageWidth: number;
It just happens that there is, at the moment, no use for it.

The width is included because the application needs to know the width used by this code when the document was processed in order to correctly translate the `left` and `right` properties of `ClientRect` values into page-relative coordinates (if desired). Since a paginated document only moves left and right, there is never a need to do this translation for the `top` and `bottom` properties and thus there is no need to know the height for this purpose. If the client did want to know the height for something else, it could always just evaluate `window.innerHeight`, `window.outerHeight`, `screen.height`, or whatever it wished as appropriate.

I did consider doing the translation in TypeScript rather than having the app do it. This would be trivial.

As silly as it may sound, the reason I decided against it is that `ClientRect` values specifically are supposed to refer to locations within the document itself and _not_ locations relative to a specific page. I suppose I could just do the translation in TypeScript and define a `PageRelativeRect` type synonym for `ClientRect` and change the definition of `Line` appropriately, but this would mean `Line` would really contain a `ClientRect` after `linesOfSpans` and only contain a `PageRelativeRect ` after `pagesOfLines` (because I need the original `ClientRect` for `pagesOfLines` to do what it does). 

For the sake of "simplicity", I just left every `ClientRect` as-is and left translation up to the application if needs to do it. The accessibility API for iOS happens to need to do the translation, but this may not always be the case and the app may want to know the original location within the document itself.

…

I'll see what I can do!

2017-02-22 14:20 UTC, aslagle commented on src/LineByLineAccessibility.ts
> +        || onNextPage;
That makes sense. I agree it would be useful to have an explanation of this somewhere and also tests would be nice :)

2017-02-22 14:23 UTC, aslagle approved these changes
I think this is good to merge :+1:

The remaining things could be addressed in another pull request.

2017-02-26 22:44 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +  pageWidth: number;
Fixed in 85bdce4f78ca7af924caed47b5a556664b3ae6f7.

2017-02-26 22:47 UTC, winniequinn commented on src/LineByLineAccessibility.ts
> +        || onNextPage;
I made [an issue](https://github.com/NYPL-Simplified/line-by-line-accessibility/issues/3) to track the additional work that will be needed around hyphenation. I'll come back to this when I have more time.

2017-02-26 22:49 UTC, merged